<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HYL-777648" name="Surefire test" tests="14" failures="14" timestamp="11 Sep 2020 09:37:58 GMT" time="30.482" errors="0">
  <testcase name="restAPITest" time="4.549" classname="com.hyland.IT.tests.IntegrationTest">
    <failure type="java.lang.Throwable" message="Connection refused: connect">
      <![CDATA[java.lang.Throwable: Connection refused: connect
	at com.hyland.IT.tests.IntegrationTest.setResultTestName(IntegrationTest.java:70)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- restAPITest -->
  <testcase name="restAPITest" time="1.937" classname="com.hyland.IT.tests.IntegrationTest">
    <failure type="java.lang.Throwable" message="Connection refused: connect">
      <![CDATA[java.lang.Throwable: Connection refused: connect
	at com.hyland.IT.tests.IntegrationTest.setResultTestName(IntegrationTest.java:70)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- restAPITest -->
  <testcase name="restAPITest" time="1.948" classname="com.hyland.IT.tests.IntegrationTest">
    <failure type="java.lang.Throwable" message="Connection refused: connect">
      <![CDATA[java.lang.Throwable: Connection refused: connect
	at com.hyland.IT.tests.IntegrationTest.setResultTestName(IntegrationTest.java:70)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- restAPITest -->
  <testcase name="restAPITest" time="1.938" classname="com.hyland.IT.tests.IntegrationTest">
    <failure type="java.lang.Throwable" message="Connection refused: connect">
      <![CDATA[java.lang.Throwable: Connection refused: connect
	at com.hyland.IT.tests.IntegrationTest.setResultTestName(IntegrationTest.java:70)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- restAPITest -->
  <testcase name="restAPITest" time="1.929" classname="com.hyland.IT.tests.IntegrationTest">
    <failure type="java.lang.Throwable" message="Connection refused: connect">
      <![CDATA[java.lang.Throwable: Connection refused: connect
	at com.hyland.IT.tests.IntegrationTest.setResultTestName(IntegrationTest.java:70)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- restAPITest -->
  <testcase name="restAPITest" time="1.929" classname="com.hyland.IT.tests.IntegrationTest">
    <failure type="java.lang.Throwable" message="Connection refused: connect">
      <![CDATA[java.lang.Throwable: Connection refused: connect
	at com.hyland.IT.tests.IntegrationTest.setResultTestName(IntegrationTest.java:70)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- restAPITest -->
  <testcase name="restAPITest" time="1.924" classname="com.hyland.IT.tests.IntegrationTest">
    <failure type="java.lang.Throwable" message="Connection refused: connect">
      <![CDATA[java.lang.Throwable: Connection refused: connect
	at com.hyland.IT.tests.IntegrationTest.setResultTestName(IntegrationTest.java:70)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- restAPITest -->
  <testcase name="restAPITest" time="1.937" classname="com.hyland.IT.tests.IntegrationTest">
    <failure type="java.lang.Throwable" message="Connection refused: connect">
      <![CDATA[java.lang.Throwable: Connection refused: connect
	at com.hyland.IT.tests.IntegrationTest.setResultTestName(IntegrationTest.java:70)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- restAPITest -->
  <testcase name="restAPITest" time="1.94" classname="com.hyland.IT.tests.IntegrationTest">
    <failure type="java.lang.Throwable" message="Connection refused: connect">
      <![CDATA[java.lang.Throwable: Connection refused: connect
	at com.hyland.IT.tests.IntegrationTest.setResultTestName(IntegrationTest.java:70)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- restAPITest -->
  <testcase name="restAPITest" time="1.922" classname="com.hyland.IT.tests.IntegrationTest">
    <failure type="java.lang.Throwable" message="Connection refused: connect">
      <![CDATA[java.lang.Throwable: Connection refused: connect
	at com.hyland.IT.tests.IntegrationTest.setResultTestName(IntegrationTest.java:70)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- restAPITest -->
  <testcase name="restAPITest" time="1.933" classname="com.hyland.IT.tests.IntegrationTest">
    <failure type="java.lang.Throwable" message="Connection refused: connect">
      <![CDATA[java.lang.Throwable: Connection refused: connect
	at com.hyland.IT.tests.IntegrationTest.setResultTestName(IntegrationTest.java:70)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- restAPITest -->
  <testcase name="restAPITest" time="1.927" classname="com.hyland.IT.tests.IntegrationTest">
    <failure type="java.lang.Throwable" message="Connection refused: connect">
      <![CDATA[java.lang.Throwable: Connection refused: connect
	at com.hyland.IT.tests.IntegrationTest.setResultTestName(IntegrationTest.java:70)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- restAPITest -->
  <testcase name="restAPITest" time="1.918" classname="com.hyland.IT.tests.IntegrationTest">
    <failure type="java.lang.Throwable" message="Connection refused: connect">
      <![CDATA[java.lang.Throwable: Connection refused: connect
	at com.hyland.IT.tests.IntegrationTest.setResultTestName(IntegrationTest.java:70)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- restAPITest -->
  <testcase name="restAPITest" time="1.94" classname="com.hyland.IT.tests.IntegrationTest">
    <failure type="java.lang.Throwable" message="Connection refused: connect">
      <![CDATA[java.lang.Throwable: Connection refused: connect
	at com.hyland.IT.tests.IntegrationTest.setResultTestName(IntegrationTest.java:70)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- restAPITest -->
</testsuite> <!-- Surefire test -->
